# Generated by Django 3.2 on 2024-02-20 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drfdemo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo2',
            old_name='tag',
            new_name='tags',
        ),
    ]
